spring:
    datasource:
        url: jdbc:postgresql://${DATABASE_URL:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:rentowne}
        username: ${DATABASE_USERNAME:postgres}
        password: ${DATABASE_PASSWORD:postgres}
        driver-class-name: org.postgresql.Driver
    liquibase:
        change-log: classpath:db/changelog/changeLog.xml
        enabled: true
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        generate-ddl: false
        properties:
            hibernate:
#                format_sql: true
                show_sql: false
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    mail:
        host: smtp.gmail.com
        port: 587
        username: rentowneApp@gmail.com
        password: pusty
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

application:
    security:
        jwt:
            secret-key: EB94B46AD4579952BED4190786541928999DEB7E5DA34A91175BFA30BEDCD92B
            expiration: 86400000 # a day
            refresh-token:
                expiration: 604800000 # 7 days
    uploadDir: "./data/apartmentImages/"
    email:
        sender: pusty
    serviceAddress: ${BACKEND_URL:http://localhost:4200}
    token:
        cleanup:
            expression: "0 0 3 * * *"

#logging:
#    level:
#        org.springframework.security: DEBUG
#        org.springframework.web: DEBUG


