spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/rentowne
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    liquibase:
        change-log: classpath:db/changelog/changeLog.xml
        enabled: true
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        generate-ddl: false
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
    security:
        jwt:
            secret-key: 49QX@#x3Wnva!h&6r!4ZhJ89fcoN83^5%v%^Na4TLv@5t8VfuKo%S!47NVZA%T%S
            expiration: 86400000 # a day
            refresh-token:
                expiration: 604800000 # 7 days
