spring:
    datasource:
        url: jdbc:postgresql://${DATABASE_URL:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:rentowne}
        username: ${DATABASE_USERNAME:postgres}
        password: ${DATABASE_PASSWORD:postgres}
        driver-class-name: org.postgresql.Driver
    liquibase:
        change-log: classpath:db/changelog/changeLog.xml
        enabled: true
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        generate-ddl: false
        properties:
            hibernate:
#                format_sql: true
                show_sql: false
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 20MB
    mail:
        host: smtp.gmail.com
        port: 587
        username: rentowneApp@gmail.com
        password: pusty
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

application:
    security:
        jwt:
            secret-key: secret-key
            expiration: 86400000 # a day
            refresh-token:
                expiration: 604800000 # 7 days
    uploadDir: "./data/apartmentImages/"
    email:
        sender: pusty
    serviceAddress: frontendAddress
    token:
        cleanup:
            expression: "0 0 3 * * *"
    payments:
        p24:
            testMode: true
            url: https://secure.przelewy24.pl
            apiUrl: https://secure.przelewy24.pl/api/v1
            merchantId: 0
            posId: 0
            urlReturn: frontendAddress
            urlStatus: backendAddress
            crc: crc
            secretKey: secretKey

            testUrl: https://sandbox.przelewy24.pl
            testApiUrl: https://sandbox.przelewy24.pl/api/v1
            testUrlReturn: frontendAddress
            testUrlStatus: backendAddress
            testCrc: de89c8bcb3a2783c
            testSecretKey: 5203bae4813b4c4301f333f0097b165a

            servers:
                - 91.216.191.181
                - 91.216.191.182
                - 91.216.191.183
                - 91.216.191.184
                - 91.216.191.185
                - 5.252.202.255
                - 5.252.202.254

logging:
    level:
        org.springframework.web: DEBUG
#        org.springframework.security: DEBUG
#        org.springframework.web.servlet.DispatcherServlet: TRACE
#        org.springframework.web.client.RestTemplate: DEBUG
#        org.springframework.http.converter.json: DEBUG
#        org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG


